trigger:
- none
pr:
- none
schedules:
- cron: "0 */2 * * *"
  branches:
    include:
    - master
  always: true
steps:
  - script: dotnet run -p src/DiscoverDotnet/DiscoverDotnet.csproj -v m -- deploy
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      NETLIFY_TOKEN: $(NETLIFY_TOKEN)
      ALGOLIA_TOKEN: $(ALGOLIA_TOKEN)
